# Generated by Django 4.2.19 on 2025-02-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyassistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
    ]
