# Generated by Django 4.2.19 on 2025-03-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyassistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='vnc_port',
            field=models.PositiveIntegerField(default=6080),
        ),
    ]
