# Generated by Django 4.2.19 on 2025-04-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyassistant', '0002_host_vnc_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
