# Generated by Django 4.2.19 on 2025-03-17 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyassistant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_space', models.FloatField()),
                ('used_space', models.FloatField()),
                ('free_space', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='pyassistant.host')),
            ],
        ),
    ]
